name: Run shared

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-shared:
    name: Trigger shared wf
    uses: agencyanalytics/infrastructure/app-v2/.github/workflows/playwright-tests.yml@CU-860r03pv3_Create-a-shared-GHA-for-Playwright_Ihor-Skliar
    with:
      browser: 'chromium'
      project: 'setup'
      stagingId: 'dummy'
