name: Run shared

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-shared:
    name: Trigger shared wf
    uses: ./.github/workflows/shared.yml
    with:
      path: /my/dummy/path
