name: Run Playwright End-to-End Tests
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
jobs:
  trigger-playwright-test:
    name: Run WF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: LOG
        run: echo ${{ inputs.path }}
